### ISSUE TITLE
Undefined objects in predict.bruSDM leading to errors

### ISSUE THREAD

**Issue by RRTogunov** [PhilipMostert/PointedSDMs#12]
See line comments:
- https://github.com/PhilipMostert/PointedSDMs/commit/23d50672db08dcf347ae3111b1eee89ee12f0b9f#r141274996

I receive an error on line [368] (https://github.com/PhilipMostert/PointedSDMs/blob/cba293af1eca4f5b89626a7681f25f732306c70d/R/bruSDM_predict.R#L368) of predict.bruSDM
``` 
formula_components <- c(covariates, intercept_terms, spatial_obj, marks_spatial, marks_intercepts)
```
that `Error: object `intercept_terms` not found` (also that `marks_spatial` and `marks_intercepts` are not found). In my case, the logical `if (!is.null(unlist(object[['species']][['speciesIn']])))` is `FALSE`, so the code doesn't correctly define `intercept_terms` or `marks_intercepts`. Similarly, the logical `if (spatial)` ([link](https://github.com/PhilipMostert/PointedSDMs/blob/cba293af1eca4f5b89626a7681f25f732306c70d/R/bruSDM_predict.R#L345)) is also `FALSE` for me, so `marks_spatial` was also undefined.

**Comment by PhilipMostert** [comment]
The issue here was due to an over-extended curly bracket and neglecting the `marks_spatial` object in the prediction. This has been fixed in the latest push.
