### ISSUE TITLE
Syntactic error in if(...) {...} else {...} code in bruSDM_predict

### ISSUE THREAD

**Issue by RRTogunov** [PhilipMostert/PointedSDMs#13]
Line comment: https://github.com/PhilipMostert/PointedSDMs/commit/23d50672db08dcf347ae3111b1eee89ee12f0b9f#r141274248

I think all the "else" statements in bruSDM_predict.R should all be on the previous line. At least on my system/R version, I cannot have a line of code start with an `else`. For example, the theoretical code   
```
if(FALSE) {"Yes"}
else {"No"}
```
returns `Error: unexpected 'else' in "  else"`. instead, it would have to be
```
if(FALSE) {
   "Yes"
} else {
    "No"
}
```
I get that error on Line [118](https://github.com/PhilipMostert/PointedSDMs/blob/cba293af1eca4f5b89626a7681f25f732306c70d/R/bruSDM_predict.R#L118), which should be `} else {`. similarly, line 126 should be 
```
if (is.null(species)) {
    speciesin <- unique(unlist(object[['species']][['speciesIn']]))
} else {
    speciesin <- species`
}
``` 
This seems to be an issue with every instance of `else` in this file.

**Comment by RRTogunov** [comment]
Update:
it seems like the function runs despite having `else` as start of lines, but it returns the `unexpected 'else' in "  else"` when executing the code in debugging/browser mode.

**Comment by PhilipMostert** [comment]
Thanks for checking this. Maybe not the best coding practices, but maybe I'll keep it as is if it works
