### ISSUE TITLE
no ebird? - Spatiotemporal vignette 

### ISSUE THREAD

**Issue by lgamador** [PhilipMostert/PointedSDMs#14]
Hello, 

I am interested in using this package. My research deals with different data types and questions regarding space/time, and this looks awesome! I am going through the 'Spatiotemoral.Rmd' vignette to help me understand general data formatting and model set up (I am relatively new to SDMs). 

I am having some issues with pulling the ebird data. The data for each year are empty. I am not sure if this is a 'spocc' issue or R version mismatch. 

Also the 'USAboundaries package has been archived? I used geodata::gadm() to remediate this (a terra object though) since it's currently up to date with R version updates. 

Thanks!

**Comment by PhilipMostert** [comment]
Hi! I'm currently doing lots of little changes to fix parts of the package, so the default Github branch and CRAN submission are both outdated. I plan on making a full change on both in the next week or so. If you would like to try the vignette now, could you try installing the _main_ branch on Github: `devtools::install_github('PhilipMostert/PointedSDMs@main')`, and that should work.

**Comment by lgamador** [comment]
Sounds good and thank you!
