### ISSUE TITLE
Predict code error

### ISSUE THREAD

**Issue by melissaminter1602** [PhilipMostert/PointedSDMs#15]
predictions <- predict(model, mesh = Mesh$mesh, 
                      mask = ROI, 
                     spatial = TRUE,
                      fun = 'linear')

Error in .Call(list(name = "CppField__get", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address

Hi, I created my model and was using this code to get prediction plots, this was running for around 24 hours until it stopped with this error. Any ideas?

Many thanks for your help
Melissa

**Comment by PhilipMostert** [comment]
Hi! Did you save the model object or the covariates and then reloaded them back into the R-session? I think that would cause this issue. For now it might be best to estimate the model and predict in the same session, but I will need to find a fix for this too.

**Comment by melissaminter1602** [comment]
Hi yes that was the problem thanks!
