### ISSUE TITLE
Error plotting spatial block

### ISSUE THREAD

**Issue by melissaminter1602** [PhilipMostert/PointedSDMs#16]
> model_setup$spatialBlock(k = 6, rows_cols = c(3,3), plot = T, seed = 1234)

Error in MtrxSet(x, dim, type = "POLYGON", needClosed = TRUE) : 
  polygons not (all) closed

This works when plot = F, but not when T, any ideas? 
Many thanks
Melissa

**Comment by PhilipMostert** [comment]
Hi, could you specify the `Boundary` argument when you start the model. Or otherwise there's issues creating a polygon object from your mesh, so try changing that and see if it works
