### ISSUE TITLE
Bias layer for one PO dataset

### ISSUE THREAD

**Issue by melissaminter1602** [PhilipMostert/PointedSDMs#20]
Hello,

I have a model with two PO data sets, but I want to define a different bias layer for each, is this possible to do in this package? E.g. is it possible to define biasFormula individually for each data set?

Thanks in advance for your help
Melissa

**Comment by PhilipMostert** [comment]
Hi,

Not sure if it is possible to use the biasFormula, although that should be a todo for the future. Think the best way to do it is to use the `.$updateFormula` function, and remove the components from each dataset. ie something like `.$updateFormula(data1, ~ - bias2)` and `.$updateFormula(data2, ~ - bias1)`

**Comment by melissaminter1602** [comment]
Fab - yes that works thank you very much.
