### ISSUE TITLE
Spatial Predictions error - "SpatialPoints" and "crs"

### ISSUE THREAD

**Issue by BrentPease1** [PhilipMostert/PointedSDMs#3]
I have been working through the vignettes with my personal data and everything has been going well up until I attempted to predict from my fieldsModel. I get the following error: Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘proj4string<-’ for signature ‘"SpatialPoints", "crs"’

I have cross-checked object structure with those provided in the vignettes and everything seems to be similar. Without having a reprex in hand, is there any direction you can point me in to solve this? I can package everything up and send over, if needed.

**Comment by PhilipMostert** [comment]
Hi Brent, do you mind please sending me the data you are working with? I could try to have a look at it then.

**Comment by BrentPease1** [comment]
Hello,

Data, sample script, and session info attached. Thanks!
[prediction_issue.zip](https://github.com/PhilipMostert/PointedSDMs/files/9261685/prediction_issue.zip)

**Comment by PhilipMostert** [comment]
Hi, I think this is more of an _sp_ issue, but the code seems to work if you change the _crs_ of the mesh before running the predictions, like so:

`box_mesh$crs <- sp_crs

spatial_predictions <- predict(fieldsModel, 
                               mesh = box_mesh,
                               mask = pred_box,
                               spatial = TRUE,
                               fun = 'linear')
`
