### ISSUE TITLE
Vulnerability to retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [PhilipMostert/PointedSDMs#7]
See https://r-spatial.org/r/2023/05/15/evolution4.html, https://r-spatial.github.io/evolution/ for background. `rgdal` which `inlabru` imports will be archived in October 2023. This means that `inlabru` will not load if `rgdal` is not on the library path. See progress on updating `inlabru` on https://github.com/inlabru-org/inlabru/issues/178.

**Comment by rsbivand** [comment]
@PhilipMostert Seems to be resolved by `inlabru 2.8.0`, check log with `sp` status 2 and without retiring packages on library path: 
[00check.log](https://github.com/PhilipMostert/PointedSDMs/files/12026474/00check.log)

**Comment by PhilipMostert** [comment]
Thank you for the reminder! I've slowly started to wean off `sp` and I'm currently moving everything over in the package to `sf`.

**Comment by rsbivand** [comment]
Looks OK when checking without retiring packages on the library path: 
[00check.log](https://github.com/PhilipMostert/PointedSDMs/files/12253703/00check.log)
