### ISSUE TITLE
Integrate predictions?

### ISSUE THREAD

**Issue by hrlai** [PhilipMostert/PointedSDMs#9]
Hi there, would it be possible to integrate the predictions to lower resolutions? 

My gut feeling is that it is somewhat similar to the residual examples [here](https://inlabru-org.github.io/inlabru/articles/2d_lgcp_residuals.html#code-appendix), but I wish to do it for the predicted values instead. Is it some combined use of `fm_int` and `inla.spde.make.A`? I also don't know how the "new data" should go into `predict.bruSDM`...

Thanks.

**Comment by PhilipMostert** [comment]
Hey, I'm not too sure if that is the correct way to do it, but if you would like to try it, the `predict.bruSDM` function should work the same as the `predict.bru` function. So you could supply the `fm_int` or `inla.spde.make.A` object into the `new_data` argument as you would normally.
